#![allow(clippy::empty_line_after_doc_comments)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(clippy::ifs_same_cond)]
#![allow(clippy::nonminimal_bool)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::manual_clamp)]
#![allow(clippy::derivable_impls)]
#![allow(clippy::excessive_nesting)]
#![allow(clippy::if_same_then_else)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::cognitive_complexity)]
#![allow(clippy::must_use_candidate)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::panic)]
#![allow(clippy::wildcard_imports)]
#![allow(clippy::cast_precision_loss)]
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::cast_sign_loss)]
#![allow(clippy::cast_possible_wrap)]
#![allow(clippy::float_cmp)]
#![allow(clippy::unreadable_literal)]
#![allow(clippy::struct_excessive_bools)]
#![allow(clippy::default_trait_access)]
#![allow(clippy::match_same_arms)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::redundant_closure_for_method_calls)]
#![allow(clippy::uninlined_format_args)]
#![allow(clippy::expect_used)]
#![allow(clippy::unwrap_used)]
#![allow(clippy::map_unwrap_or)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::unused_self)]
#![allow(clippy::unused_async)]
#![allow(clippy::assigning_clones)]
#![allow(clippy::case_sensitive_file_extension_comparisons)]
#![allow(clippy::cast_lossless)]
#![allow(clippy::fn_params_excessive_bools)]
#![allow(clippy::format_push_string)]
#![allow(clippy::if_not_else)]
#![allow(clippy::ignored_unit_patterns)]
#![allow(clippy::items_after_statements)]
#![allow(clippy::manual_let_else)]
#![allow(clippy::manual_string_new)]
#![allow(clippy::needless_continue)]
#![allow(clippy::no_effect_underscore_binding)]
#![allow(clippy::redundant_else)]
#![allow(clippy::ref_option)]
#![allow(clippy::return_self_not_must_use)]
#![allow(clippy::single_char_pattern)]
#![allow(clippy::single_match_else)]
#![allow(clippy::unnecessary_semicolon)]
#![allow(clippy::unnested_or_patterns)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::if_then_some_else_none)]
#![allow(clippy::unused_unit)]
#![allow(clippy::duration_subsec)]
#![allow(clippy::bool_to_int_with_if)]
#![allow(clippy::bool_comparison)]
#![allow(clippy::similar_names)]
#![allow(clippy::bool_assert_comparison)]
#![allow(clippy::struct_field_names)]
#![allow(missing_docs)]
#![allow(unknown_lints)]

//! # Memory CLI Library
//!
//! This library provides the core functionality for the memory-cli command-line tool.
//! It includes error handling, test utilities, and command implementations.

pub mod commands;
pub mod config;
pub mod errors;
pub mod output;
pub mod test_utils;
