#!/usr/bin/env bash
# generate-contract-docs.sh — D3.2b generate CLI/MCP contract summary
#
# Usage:
#   ./scripts/generate-contract-docs.sh
#   ./scripts/generate-contract-docs.sh --check

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT_DIR="docs/generated"
OUT_FILE="$OUT_DIR/cli-mcp-summary.md"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

fail() {
  echo "HARNESS VIOLATION: contract-docs — $1" >&2
  exit 1
}

generate() {
  mkdir -p "$OUT_DIR"

  local tools_tmp
  tools_tmp=$(mktemp)

  # Extract MCP tool names from Tool::new(\n "name"...) (multiline).
  # Prefer production sources; exclude tests/ to reduce fixture noise.
  if [[ -d memory-mcp/src ]]; then
    {
      # -U: Tool::new often spans lines: Tool::new(\n  "query_memory".to_string(),
      rg -oN --no-filename -U 'Tool::new\(\s*"([a-z][a-z0-9_]*)"' -r '$1' \
        memory-mcp/src \
        --glob '!**/*test*' \
        --glob '!**/*tests*' \
        2>/dev/null || true
    } | sort -u \
      | rg -v '^(custom_tool|temp_tool|test|agentfs)$' \
      >"$tools_tmp" || true
  else
    : >"$tools_tmp"
  fi

  local tool_count
  tool_count=$(wc -l <"$tools_tmp" | tr -d ' ')

  {
    echo "# CLI / MCP Contract Summary"
    echo
    echo "Generated by \`scripts/generate-contract-docs.sh\`."
    echo "Do not hand-edit; re-run the generator after tool/CLI changes."
    echo
    echo "Generated: $(date -u +%Y-%m-%dT%H:%MZ)"
    echo
    echo "## CLI"
    echo
    echo "- Binary / package: **do-memory-cli** (crate \`memory-cli\` / package \`do-memory-cli\`)"
    echo "- Primary groups (from README / AGENTS): episode, pattern, storage, config, health,"
    echo "  backup, monitor, logs, eval, embedding, completion, tag, relationship, playbook, feedback"
    echo "- Config: \`config init\` / \`config show-template\` / \`config validate\` / \`config check\`"
    echo
    echo "## MCP server"
    echo
    echo "- Package: **do-memory-mcp** (binary \`do-memory-mcp-server\`)"
    echo "- Source of tool registry: \`memory-mcp/src\` (grep-extracted names below)"
    echo
    if [[ "$tool_count" -eq 0 ]]; then
      echo "_No tool names extracted — memory-mcp sources missing or pattern mismatch._"
      echo
      echo "Regenerate after adding tools, or inspect:"
      echo "\`rg 'Tool::new\\(' memory-mcp/src\`"
    else
      echo "Tool count (unique grep hits): **$tool_count**"
      echo
      echo "| # | Tool name |"
      echo "|---|-----------|"
      local i=0
      while IFS= read -r t; do
        [[ -z "$t" ]] && continue
        i=$((i + 1))
        echo "| $i | \`$t\` |"
      done <"$tools_tmp"
    fi
    echo
    echo "## Notes"
    echo
    echo "- Batch tools (\`batch_query_episodes\`, etc.) may be intentionally deferred."
    echo "- \`execute_agent_code\` is fail-closed / unavailable (WASM sandbox removed)."
    echo "- Keep this file under 100 lines; full schemas live in source and \`docs/API_REFERENCE.md\`."
    echo
  } >"$OUT_FILE"

  rm -f "$tools_tmp"

  local lines
  lines=$(wc -l <"$OUT_FILE" | tr -d ' ')
  if [[ "$lines" -gt 100 ]]; then
    fail "generated $OUT_FILE has $lines lines (limit 100); trim extractor or table"
  fi

  echo "OK: wrote $OUT_FILE ($lines lines, tools=$tool_count)"
}

if [[ "$CHECK" -eq 1 ]]; then
  if [[ ! -f "$OUT_FILE" ]]; then
    echo "Missing $OUT_FILE — generating..."
    generate
    if [[ ! -f "$OUT_FILE" ]]; then
      fail "could not generate $OUT_FILE; run: ./scripts/generate-contract-docs.sh"
    fi
    echo "OK: --check generated missing $OUT_FILE"
  else
    # Re-generate to a temp and compare for drift (soft regenerate in place is fine for CI)
    generate
    echo "OK: --check refreshed $OUT_FILE"
  fi
else
  generate
fi
