#!/usr/bin/env bash
# generate-llms-txt.sh - Regenerate the compact `llms.txt` LLM context file and,
# optionally, a full `llms-full.txt` artifact.
#
# `llms.txt` is TRACKED and kept high-signal (project purpose, crate map, current
# commands, key invariants, and links to planning docs). `llms-full.txt` is an
# ARTIFACT ONLY (git-ignored) because it concatenates large planning/agent docs
# and changes frequently.
#
# Usage:
#   scripts/generate-llms-txt.sh            Regenerate llms.txt in place
#   scripts/generate-llms-txt.sh --full     Also write llms-full.txt (artifact)
#   scripts/generate-llms-txt.sh --check    CI freshness check (non-zero if stale)
#   scripts/generate-llms-txt.sh -h|--help  Show this help
#
# The generator never writes temporary files to the repository root; scratch
# output goes under target/ (or $CARGO_TARGET_DIR when set).

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

MODE="write"
WRITE_FULL="false"

usage() {
  sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

for arg in "$@"; do
  case "$arg" in
    --full) WRITE_FULL="true" ;;
    --check) MODE="check" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; usage >&2; exit 1 ;;
  esac
done

cd "$PROJECT_ROOT"

# --- Dynamic inputs -----------------------------------------------------------

# Workspace version from Cargo.toml (single source of truth).
VERSION=$(grep -E '^version\s*=\s*"[0-9]+\.[0-9]+\.[0-9]+"' Cargo.toml \
  | head -1 | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
if [[ -z "${VERSION:-}" ]]; then
  echo "error: could not detect workspace version from Cargo.toml" >&2
  exit 1
fi

# Crate map: publishable do-memory-* crates with descriptions.
crate_rows() {
  if command -v jq >/dev/null 2>&1; then
    cargo metadata --no-deps --format-version 1 2>/dev/null \
      | jq -r '.packages[]
          | select(.name | startswith("do-memory"))
          | select(.description != null and .description != "")
          | "| `\(.name)` | \(.description) |"' \
      | sort
  fi
}

CRATE_ROWS="$(crate_rows)"
if [[ -z "$CRATE_ROWS" ]]; then
  # Fallback keeps the generator working without cargo/jq.
  CRATE_ROWS=$(cat <<'FALLBACK'
| `do-memory-core` | Core memory types, episode management, pattern extraction |
| `do-memory-storage-turso` | Turso/libSQL persistent storage backend |
| `do-memory-storage-redb` | redb cache storage backend |
| `do-memory-mcp` | MCP server implementation |
| `do-memory-cli` | Command-line interface |
| `do-memory-test-utils` | Testing utilities |
FALLBACK
)
fi

# --- Compact llms.txt ---------------------------------------------------------

render_llms_txt() {
  cat <<EOF
# Self-Learning Memory System - LLM Context

> Generated by \`scripts/generate-llms-txt.sh\`. Do not edit by hand; run the
> script to refresh. Version is sourced from the workspace \`Cargo.toml\`.

## Project Overview

A Rust-based self-learning memory system with episodic memory, pattern
extraction, and intelligent retrieval for AI coding agents.

**Repository**: https://github.com/d-o-hub/rust-self-learning-memory
**Language**: Rust (Edition 2024)
**Version**: ${VERSION}

## Architecture

### Crates

| Crate | Purpose |
|-------|---------|
${CRATE_ROWS}

### Key Modules

- **Episode Management**: Create, log steps, complete episodes
- **Pattern Extraction**: Extract patterns from episode history
- **Memory Retrieval**: Semantic search + CPU-local cascade (BM25/HDC/ConceptGraph)
- **Recommendation System**: Suggest patterns and playbooks from context
- **Attribution**: Track recommendation sessions and feedback

## Build & Test Commands

\`\`\`bash
./scripts/build-rust.sh dev        # Build (dev|release|check|clean)
cargo nextest run --all            # Run tests
cargo test --doc                   # Run doctests
./scripts/code-quality.sh fmt      # Format
./scripts/code-quality.sh clippy --workspace
./scripts/quality-gates.sh         # All quality gates (coverage >=90%)
\`\`\`

## Key Invariants (from AGENTS.md)

- **Async**: Tokio everywhere; no blocking (use \`spawn_blocking\`)
- **Storage**: Parameterized SQL only; no locks held across \`.await\`
- **Serialization**: Postcard (not bincode)
- **Clippy**: Zero warnings (\`-D warnings\`); fix, don't suppress
- **Files**: <=500 LOC per source file
- **Tests**: >=90% coverage; \`#[tokio::test]\` for async; AAA pattern
- **Docs**: Wrap URLs in \`<...>\`; re-export new public types from \`lib.rs\`

## Environment Variables

- \`TURSO_DATABASE_URL\` - Turso database URL (\`http://127.0.0.1:8080\` for local dev)
- \`TURSO_AUTH_TOKEN\` - Turso auth token (empty for local dev)
- \`OPENAI_API_KEY\` - OpenAI API key for embeddings
- \`MCP_OAUTH_TOKEN_SECRET\` - HMAC secret for MCP OAuth/JWT verification

## Binaries

- \`do-memory-mcp-server\` - MCP server (lazy tool registry, ADR-024)
- \`do-memory-cli\` - CLI (episode/pattern/tag/relationship commands)

## Documentation & Planning

- \`AGENTS.md\` - Agent coding guidelines and invariants
- \`agent_docs/\` - Detailed build/test/architecture docs
- \`plans/ROADMAPS/ROADMAP_ACTIVE.md\` - Active roadmap
- \`plans/STATUS/CURRENT.md\` - Current sprint status
- \`plans/GOAP_STATE.md\` - GOAP execution state
- \`plans/adr/\` - Architecture Decision Records
- \`docs/API_REFERENCE.md\` - MCP tool reference

## Regenerating This File

\`\`\`bash
scripts/generate-llms-txt.sh          # refresh llms.txt
scripts/generate-llms-txt.sh --full   # also write llms-full.txt (artifact)
scripts/generate-llms-txt.sh --check  # CI freshness check
\`\`\`
EOF
}

# --- Full llms-full.txt artifact ---------------------------------------------

render_llms_full() {
  render_llms_txt
  local doc
  for doc in \
    AGENTS.md \
    agent_docs/building_the_project.md \
    agent_docs/running_tests.md \
    agent_docs/code_conventions.md \
    agent_docs/service_architecture.md \
    plans/STATUS/CURRENT.md \
    plans/ROADMAPS/ROADMAP_ACTIVE.md; do
    if [[ -f "$doc" ]]; then
      printf '\n\n---\n\n# APPENDIX: %s\n\n' "$doc"
      cat "$doc"
    fi
  done
}

# --- Execute ------------------------------------------------------------------

TARGET_DIR="${CARGO_TARGET_DIR:-$PROJECT_ROOT/target}"
mkdir -p "$TARGET_DIR"

if [[ "$MODE" == "check" ]]; then
  tmp="$TARGET_DIR/llms.txt.check"
  render_llms_txt > "$tmp"
  if ! diff -q "$tmp" "$PROJECT_ROOT/llms.txt" >/dev/null 2>&1; then
    echo "error: llms.txt is stale. Run scripts/generate-llms-txt.sh to update." >&2
    diff -u "$PROJECT_ROOT/llms.txt" "$tmp" || true
    rm -f "$tmp"
    exit 1
  fi
  rm -f "$tmp"
  echo "[llms] llms.txt is up to date (v${VERSION})"
  exit 0
fi

render_llms_txt > "$PROJECT_ROOT/llms.txt"
echo "[llms] Wrote llms.txt (v${VERSION})"

if [[ "$WRITE_FULL" == "true" ]]; then
  render_llms_full > "$PROJECT_ROOT/llms-full.txt"
  echo "[llms] Wrote llms-full.txt artifact (git-ignored)"
fi
