#!/usr/bin/env bash
# install-hooks.sh — activate and verify the local sensors declared in .pre-commit-config.yaml
#
# A fresh clone has no hooks installed, so every sensor the config declares (fmt, loc,
# file hygiene, shellcheck, yamllint, commitlint) is inert and the first feedback an agent
# gets is a failed CI run. `pre-commit install` alone is not enough either: the commitlint
# hook is declared in the commit-msg stage, which the default install does not create.
#
# Usage:
#   ./scripts/install-hooks.sh            # install both stages + fetch hook environments
#   ./scripts/install-hooks.sh --verify   # fail if an expected hook is not installed
#   ./scripts/install-hooks.sh --status   # report what is installed, always exit 0

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

MODE="install"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verify)
      MODE="verify"
      ;;
    --status)
      MODE="status"
      ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      sed -n '2,12p' "$0" >&2
      exit 1
      ;;
  esac
  shift
done

# Linked worktrees share the common git dir, so --git-path hooks resolves to one directory
# for the whole clone: a single install covers every worktree, and a single absence disables
# sensors in all of them.
HOOKS_DIR="$(git rev-parse --git-path hooks)"
if [[ "$HOOKS_DIR" != /* ]]; then
  HOOKS_DIR="$ROOT/$HOOKS_DIR"
fi

EXPECTED=(pre-commit commit-msg)

# pre-commit stamps every hook it generates with this header line; matching it distinguishes
# a real generated hook from a stray or hand-written file of the same name.
HOOK_MARKER="File generated by pre-commit"

is_installed() {
  local stage="$1"
  [[ -x "$HOOKS_DIR/$stage" ]] && grep -q "$HOOK_MARKER" "$HOOKS_DIR/$stage" 2>/dev/null
}

stage_line() {
  local stage="$1"
  if is_installed "$stage"; then
    echo "installed: $stage"
  else
    echo "INERT: $stage (declared in .pre-commit-config.yaml, never runs)"
  fi
}

report() {
  local stage
  for stage in "${EXPECTED[@]}"; do
    stage_line "$stage"
  done
  echo "hooks_dir=$HOOKS_DIR (shared by $(git worktree list --porcelain | grep -c '^worktree ') worktrees)"
}

if [[ "$MODE" == "status" ]]; then
  report
  exit 0
fi

if [[ "$MODE" == "verify" ]]; then
  missing=0
  stage=""
  for stage in "${EXPECTED[@]}"; do
    stage_line "$stage"
    if is_installed "$stage"; then
      continue
    fi
    echo "HARNESS VIOLATION: local-hooks — $stage hook missing, so the sensors it runs" \
      "never fire locally (fix: ./scripts/install-hooks.sh)" >&2
    missing=$((missing + 1))
  done
  if [[ "$missing" -gt 0 ]]; then
    exit 1
  fi
  echo "OK: all expected local sensor hooks are active"
  exit 0
fi

if ! command -v pre-commit >/dev/null; then
  echo "HARNESS VIOLATION: local-hooks — pre-commit not on PATH" >&2
  echo "Install it first: pip install pre-commit (or pipx install pre-commit)" >&2
  exit 1
fi

if [[ ! -f "$ROOT/.pre-commit-config.yaml" ]]; then
  echo "HARNESS VIOLATION: local-hooks — .pre-commit-config.yaml not found at repo root" >&2
  exit 1
fi

# --hook-type is repeated because the default installs only 'pre-commit'; commitlint lives
# in the commit-msg stage and would otherwise stay inert on a machine that followed the
# config header to the letter.
pre-commit install --hook-type pre-commit --hook-type commit-msg
pre-commit install-hooks

echo ""
report
